################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
footer_content = "An interdisciplinary team of coders, analysts and user experience specialists dedicated to building enterprise applications and premium digital products that bring your ideas to life, delight your users and help you achieve your goals."
# copyright
copyright = " © {year} Spritle Software. All Rights Reserved."
title= "Spritle Software |  Advanced Web & Mobile Solutions"
policy = "Privacy Policy"




################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
# copyright
copyright = "© 2021 Spritle Software. All Rights Reserved."