############# French navigation ##############
# main menu

[[main]]
name = "Our Works"
url = "work/"
weight = 1

[[main]]
name = "Services"
weight = 2

  [[main]]
  parent = "Services"
  name = "Home"
  url =  "services/"
  weight= 1

  [[main]]
  parent = "Services"
  name = "Web Apps Development"
  url =  "web_application_development_services/"
  weight = 2

  [[main]]
  parent = "Services"
  name = "Mobile Apps Development"
  url =  "mobile_service/"
  weight= 3

  [[main]]
  parent = "Services"
  name = "AI & ML Application Development Services"
  url =  "ai-ml-application-development-services/"
  weight=4

[[main]]
name = "Products"
weight = 4

  [[main]]
  parent = "Products"
  name = "Freshworks Apps"
  url =  "products/freshworks/"

  [[main]]
  parent = "Products"
  name = "Zoho Apps"
  url =  "products/zoho/"

  [[main]]
  parent = "Products"
  name = "Ruby Gems"
  url =  "products/rubygems"  

  [[main]]
  parent = "Products"
  name = "Minoot"
  url =  "products/minoot"  

  [[main]]
  parent = "Products"
  name = "Voicebot"
  url =  "products/voicebot" 

[[main]]
name = "Company"
weight = 5 
hasChildren = true

  [[main]]
  parent = "Company"
  name = "Our Process"
  url =  "process/"
  weight=1

  [[main]]
  parent = "Company"
  name = "Knowledge Sharing"
  url = "knowledge_sharing/"
  weight=2

  [[main]]
  parent = "Company"
  name = "About us"
  url = "about/"
  weight=3

  [[main]]
  parent = "Company"
  name = "Careers"
  url = "career/"
  weight=4

  [[main]]
  parent = "Company"
  name = "Latest News"
  url = "latest_news/"
  weight=5

[[main]]
name = "Blog"
url = "blog/"
weight = 6

[[main]]
name = "Contact"
url = "contact/"
weight = 7


# Footer menu
[[footer]]
name = "Web Apps Development"
url = "web_application_development_services/"
weight = 1

[[footer]]
name = "Mobile Apps Development"
url = "mobile_service/"
weight = 2

[[footer]]
name = "AI & ML Application Development Services"
url = "ai-ml-application-development-services/"
weight = 3

[[footer]]
name = "Saasly.in"
url = "https://saasly.in/"
weight = 4

[[footer]]
name = "healthengr.io"
url = "https://healthengr.io/"
weight = 5

[[footer]]
name = "surveillens.ai"
url = "https://www.surveillens.ai/"
weight = 6

