############# French navigation ##############
# main menu

[[main]]
name = "Our Works"
url = "our-work/"
weight = 1

[[main]]
name = "Services"
weight = 2

  [[main]]
  parent = "Services"
  name = "Home"
  url =  "services/"

  [[main]]
  parent = "Services"
  name = "Web Apps Development"
  url =  "web_application_development_services/"

  [[main]]
  parent = "Services"
  name = "Mobile Apps Development"
  url =  "mobile_service/"

  [[main]]
  parent = "Services"
  name = "AI & ML Application Development Services"
  url =  "ai-ml-application-development-services/"

[[main]]
name = "Products"
weight = 4

  [[main]]
  parent = "Products"
  name = "Freshworks Apps"
  url =  "products/freshworks/"

  [[main]]
  parent = "Products"
  name = "Zoho Apps"
  url =  "products/zoho/"

  [[main]]
  parent = "Products"
  name = "Ruby Gems"
  url =  "career/"  

[[main]]
name = "Company"
weight = 5 
hasChildren = true

  [[main]]
  parent = "Company"
  name = "Our Process"
  url =  "how-it-works/"

  [[main]]
  parent = "Company"
  name = "Knowledge Sharing"

  [[main]]
  parent = "Company"
  name = "Careers"
  url = "career/"

  [[main]]
  parent = "Company"
  name = "Latest News"

[[main]]
name = "Blog"
url = "blog/"
weight = 6

[[main]]
name = "Contact"
url = "contact/"
weight = 7


# Footer menu
[[footer]]
name = "Faq"
url = "faq/"
weight = 1

[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3