#################### default parameters ################################
# favicon
favicon = "images/favicons/favicon-96x96.png"
favicon_32x32 = "images/favicons/favicon-32x32.png"
favicon_16x16 = "images/favicons/favicon-16x16.png"
apple_touch_icon = "images/favicons/apple-icon.png"
# logo
logo_text = "Spritle Software"
logo = "images/spritle-logo.png"
logo_width = "120px;"
# OpenGraph / Twitter Card metadata
description = "TAn interdisciplinary team of coders, analysts and user experience specialists dedicated to building state-of-the-art web & mobile application.Talk to us today!"
author = "Spritle Team"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# custom script on header
custom_script= ""

# Preloader
[preloader]
enable = true
preloader = "images/preloader.png" # use jpg, png, svg or gif format.
greetings = "Welcome to"
greetings_to = "Spritle"

# navigation button
[navigation_button_bordered]
enable = true
label = "TALK TO US"
link = ""

[navigation_button_linked]
enable = true
label = "Log In"
link = ""
# Footer call to action
[footer_call_to_action]
enable = true
title = "Get your **unique & incredible ideas** kickstarted now"
[footer_cta_button]
enable = true
label = "Get in touch"
link = "contact"

# Subscription
[subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon : https://fontawesome.com/icons
link = "#"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"